Fix carousel selected state and dots
storefront-foundation/react-storefront pull request #179
Opened 2021-04-29 19:08 UTC by jasonadkison

- fixes an issue where the `selected` state was not properly calculated when looping through the first and last images in the set
- fixes the selected carousel dots styling

2021-04-29 19:12 UTC, jasonadkison commented
@dijs please give this a review asap, thanks!

2021-05-03 14:13 UTC, dijs commented on src/carousel/Carousel.js
> +    const nextSelected = Math.abs(index - count * Math.floor(index / count))
Can you please add some comments explaining this math.

2021-05-03 14:16 UTC, dijs requested changes
Looks good. Just needs some comments.

2021-05-03 16:51 UTC, jasonadkison commented
> Looks good. Just needs some comments.

@dijs I realized I couldn't easily explain what one-liner version was doing so I converted it into far simpler logic.

2021-05-03 17:22 UTC, dijs approved these changes

2021-05-03 17:23 UTC, merged